### ISSUE TITLE
Question about initiating multiple NDPs

### ISSUE THREAD

**Issue by jingyao-zhang** [hpc-ulisboa/NDPmulator#1]
Hi all,

I have read through the related paper and this work is impressive. 

My research is on near-cache computing.
Since I want to use several NDPs near the L2 cache, can current NDPmulator support multiple NDP initiation?
If I want to modify it to support multiple NDPs, what would be the suitable steps to achieve this goal?

Thanks again for your valuable work!

Best,
Jingyao

**Comment by joaomiguelvieira** [comment]
Hi, Jingyao,

Thank you for your interest in NDPmulator.

NDPmulator allows to add as many NDP devices as you want to the processing system. After having described your NDP device models, you just have to instantiate them in the Python simulation script as follows (for the purpose of this example, consider [se-run-ndp_dev_a.py](https://github.com/hpc-ulisboa/NDPmulator/blob/main/configs/ndp/se-run-ndp_dev_a.py) as a base).

Let us assume that you have two NDP devices (ndp_accel1 and ndp_accel2), and you want to couple both of them to the L2 cache.

1. First, you will have to instantiate both devices. Make sure that the addresses of the programming interfaces do not overlap (`ndp_ctrl`).
```
# Create NDP devices
system.ndp_accel1 = NDPDev1(ndp_ctrl=("0x40000000", "0x40001000"), ndp_data=("0x40001000", "0x80000000"))
system.ndp_accel2 = NDPDev2(ndp_ctrl=("0x40001000", "0x40002000"), ndp_data=("0x40001000", "0x80000000"))
```

2. Connect the control interface of both NDP devices.
```
# Connect NDP devices to the CPU and L1D to NDP devices
system.ndp_accel1.cpu_side = system.cpu.dcache_port
system.ndp_accel2.cpu_side = system.ndp_accel1.mem_side
system.cpu.dcache.cpu_side = system.ndp_accel2.mem_side
```

3. Connect the NDP devices to the L2 XBar.
```
# Connect NDP device to L2
system.ndp_accel1.dma_port = system.l2bus.cpu_side_ports
system.ndp_accel2.dma_port = system.l2bus.cpu_side_ports
```

Take into account that by having multiple NDP devices with independent LSUs coupled with the same memory level may generate unnecessary contention, and you may have tweak parameters such as `max_rsze` and `max_reqs` to make the system work (since cache will **allways** accept requests but the actual packet queue may grow beyond the limit, causing the simulation to crash. It would be preferrable to encapsulate all the NDP devices into the same model and instantiate said model just once.

**Comment by jingyao-zhang** [comment]
Hi, Joao,

Thanks for your detailed instructions!

I noticed that two NDPs are cascaded since only `ndp_accel1.cpu_side` connects to the `cpu.dcache_port`.

If I want these two NDPs directly controlled by CPU and two NDPs can issue memory requests at the same time, should I add extra modules between parallel NDPs and `cpu.dcache_port`, and also modify the cache controller to make it able to handle simultaneous requests?

**Comment by joaomiguelvieira** [comment]
Hi again, Jingyao,

In order to connect both NDP devices to the CPU and avoid dealing with some complicated overlaps in the memory mapping (which I tried before), the easiest way to to couple multiple NDP devices is to mount them like so.

In reality, NDPDev1 will bypass all requests to NDPDev2 with latency 0, so what is actually simulated is a scenario where both the NDPDev1 and the NDPDev2 are connected **directly** to the CPU. 

If you want to pursue the alternative way, you can connect the cpu.dcache port to a XBar and connect both NDP devices and the L1 data cache to that XBar. However, this will require you to redesign the memory mapping of the entire system (which is a rather complex task and there is virtually no advantage of doing so).

I hope this aswers your question!

**Comment by jingyao-zhang** [comment]
Hi Joao,

Thanks for your quick and valuable reply!
There is no question from my side (currently?).
Really appreciate your opensourced work for helping future researchers (like me)!
